#spring:
#datasource:
#druid:
#driver-class-name:com.mysql.cj.jdbc.Driver
#url:jdbc:mysql://47.120.5.13:3306/hhd?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=Asia/Shanghai
#username:"hhd"
#password:"hhd443.."

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.120.5.13:3306/workorder?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=Asia/Shanghai
    username: "hhd"
    password: "hhd443.."
